export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');
export const AUTH_PASSWORD_HASHER = Symbol('AUTH_PASSWORD_HASHER');
export const AUTH_TOKEN_SERVICE = Symbol('AUTH_TOKEN_SERVICE');
export const AUTH_REGISTRATION_FLOW_STORE = Symbol('AUTH_REGISTRATION_FLOW_STORE');

